name: fog_of_war_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  geolocator: ^14.0.2
  path_provider: ^2.1.5
  flutter_background_geolocation: ^4.18.2
  path: ^1.9.1
  sqflite: ^2.4.2
  background_fetch: ^1.5.0
  file_picker: ^10.3.8
  csv: ^6.0.0
  share_plus: ^12.0.1
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true